<div id="footer">
    <div class="h n">
        <div class="sections">
            <h5>our objectives</h5>
            <ul>
                <li>honesty</li>
                <li>reality</li>
                <li>Credibility</li>
            </ul>
        </div>
        <div class="sections">
            <h5>copy right</h5>
            <ul>
                <li>mr fifty cent</li>
                <li>MG</li>
                <li>mahmoud gad</li>
            </ul>
        </div>
        <div class="sections border-right-0">
            <ul class="footer_icons border-right-0">
                <li><img src="template/images/facebook.png"></li>
                <li><img src="template/images/1%20V7GYJQ_4lykfDzOf9q17eA.jpeg"></li>
                <li><img src="template/images/social_youtube_2756.png"></li>
                <li><img src="template/images/twitter.png"></li>
                <li><img src="template/images/1491580629-yumminkysocialmedia03_83105.png"></li>
                <li><img src="template/images/images.png"></li>
            </ul>
        </div>
    </div>
</div>
</div>
<script src="template/js/jquery-3.4.1.js"></script>
<script src="template/js/bootstrap.js"></script>
<script src="template/js/script.js"></script>
<script src="template/js/script-b.js"></script>
<script src="template/js/pages.js"></script>
<script src="template/js/current.js"></script>


</body>
</html>