<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"name="viewport"content="width=device-width, initial-scale=1.0">
    <title>Title</title>
    <link rel="stylesheet" href="template/css/bootstrap.css">
    <link rel="stylesheet" href="template/css/style.css">
</head>
<body>
<div id="wrapper">
    <div id="header">
        <div class="h">
            <div class="logo">
                <div class="inner">
                    <span>hellow</span>
                </div>
            </div>
            <div class="section-user">
                <h5 class="section-user-span">example@example.com</h5>
            </div>
        </div>
    </div>